FIX Support default tofu version

diff --git a/libexec/tofuenv-resolve-version b/libexec/tofuenv-resolve-version
--- a/libexec/tofuenv-resolve-version
+++ b/libexec/tofuenv-resolve-version
@@ -71,30 +71,18 @@ declare version_requested version regex min_required version_file;
 
 declare arg="${1:-""}";
 
-if [ -z "${arg}" -a -z "${TOFUENV_TOFU_VERSION:-""}" ]; then
-  version_file="$(tofuenv-version-file)";
-  log 'debug' "Version File: ${version_file}";
+if [ -z "${arg}" ] && [ -z "${TOFUENV_TOFU_VERSION:-""}" ]; then
+  log 'debug' 'We are not hardcoded by a TOFUENV_TOFU_VERSION environment variable';
 
-  if [ "${version_file}" != "${TOFUENV_CONFIG_DIR}/version" ]; then
-    log 'debug' "Version File (${version_file}) is not the default \${TOFUENV_CONFIG_DIR}/version (${TOFUENV_CONFIG_DIR}/version)";
-    version_requested="$(cat "${version_file}")" \
-      || log 'error' "Failed to open ${version_file}";
+  version_file="$(tofuenv-version-file)" \
+    && log 'debug' "Version file retrieved from tofuenv-version-file: ${version_file}" \
+    || log 'error' 'Failed to retrieve version file from tofuenv-version-file';
 
-  elif [ -f "${version_file}" ]; then
-    log 'debug' "Version File is the default \${TOFUENV_CONFIG_DIR}/version (${TOFUENV_CONFIG_DIR}/version)";
-    version_requested="$(cat "${version_file}")" \
-      || log 'error' "Failed to open ${version_file}";
-
-    # Absolute fallback
-    if [ -z "${version_requested}" ]; then
-      log 'debug' 'Version file had no content. Falling back to "latest"';
-      version_requested='latest';
-    fi;
-
-  else 
-    log 'debug' "Version File is the default \${TOFUENV_CONFIG_DIR}/version (${TOFUENV_CONFIG_DIR}/version) but it doesn't exist";
-    log 'debug' 'No version requested on the command line or in the version file search path. Installing "latest"';
-    version_requested='latest';
+  if [[ -f "${version_file}" ]]; then
+    version_requested="$(cat "${version_file}" || true)" \
+      && log 'debug' "Version specified in ${version_file}: ${version_requested}";
+  else
+    version_requested="${TOFUENV_TOFU_DEFAULT_VERSION:-"latest"}";
   fi;
 elif [ -n "${TOFUENV_TOFU_VERSION:-""}" ]; then
   version_requested="${TOFUENV_TOFU_VERSION}";
